<a href="https://colab.research.google.com/github/GideonCarius/Unicorn-Store-Analysis/blob/main/Unicorn_Store_Analysis_2015_2018.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Part 0: Preparations

### Installing and importing packages

In [1]:
import pandas as pd
import sqlalchemy as sa
pd.set_option('display.max_rows', 1000)
from google.colab import drive
drive.mount('/content/drive')

### Making a connection

In [12]:
unicorn_url = 'postgresql://Test:Unicorn?sslmode=require'

None

Connecting with SQLAlchemy always works in two steps:

1.   Create an engine
2.   Make a connection

In [ ]:
engine = sa.create_engine(unicorn_url)
connection = engine.connect().execution_options(isolation_level="AUTOCOMMIT")

### Schema

## Tasks:

In [ ]:
query = """
SELECT *
FROM customers
LIMIT 10
"""

display(pd.read_sql(sa.text(query),connection))

   customer_id       customer_name customer_segment
0            1       Aaron Bergman         Consumer
1            2       Aaron Hawkins        Corporate
2            3      Aaron Smayling        Corporate
3            4     Adam Bellavance      Home Office
4            5           Adam Hart        Corporate
5            6  Adam Shillingsburg         Consumer
6            7       Adrian Barton         Consumer
7            8         Adrian Hane      Home Office
8            9        Adrian Shami      Home Office
9           10         Aimee Bixby         Consumer

In [ ]:
# 1. How many customers do we have in the data?
query = """
SELECT COUNT(DISTINCT customer_id)
FROM customers
"""

display(pd.read_sql(sa.text(query),connection))

   count
0    795

In [ ]:
# 2. What was the city with the most profit for the company in 2015?
query = """
SELECT shipping_city, SUM(order_profits) AS city_profits
FROM order_details od
JOIN orders o
ON o.order_id = od.order_id
WHERE EXTRACT(YEAR FROM o.order_date) = 2015
GROUP BY shipping_city
ORDER BY city_profits DESC
LIMIT 1
"""

display(pd.read_sql(sa.text(query),connection))

   shipping_city  city_profits
0  New York City       14753.0

In [ ]:
# 3. In 2015, what was the most profitable city's profit?
query = """
SELECT shipping_city, sum(order_profits) AS total_profits
FROM order_details AS od
INNER JOIN orders AS o
ON o.order_id = od.order_id
WHERE EXTRACT(YEAR FROM o.order_date) = 2015
GROUP BY shipping_city
ORDER BY total_profits DESC
LIMIT 1;
"""

display(pd.read_sql(sa.text(query),connection))

   shipping_city  total_profits
0  New York City        14753.0

In [ ]:
# 4. How many different cities do we have in the data?
query = """
SELECT COUNT(DISTINCT shipping_city)
FROM orders
"""

display(pd.read_sql(sa.text(query),connection))

   count
0    531

In [ ]:
# 5. Show the total spent by customers from low to high.
query = """
SELECT c.customer_id AS customer_id,
SUM(od.order_sales) AS total_sales
FROM customers c
JOIN orders o on c.customer_id = o.customer_id
JOIN order_details od on o.order_id = od.order_id
GROUP BY c.customer_id
ORDER BY total_sales ASC;
"""

display(pd.read_sql(sa.text(query),connection))

     customer_id  total_sales
0            456          5.0
1            738          5.0
2            546         16.0
3            124         17.0
4            657         22.0
5            626         48.0
6            725         49.0
7            448         50.0
8              9         58.0
9            355         72.0
10           292         81.0
11            38         88.0
12           419         89.0
13           649         98.0
14           169        113.0
15           248        125.0
16            95        131.0
17           613        133.0
18           310        147.0
19           529        154.0
20           229        157.0
21           605        160.0
22            54        161.0
23           550        162.0
24            51        170.0
25           383        195.0
26            26        201.0
27           333        219.0
28           642        221.0
29           316        227.0
30           270        228.0
31           315        237.0
32           594        239.0
33           666        243.0
34           318        251.0
35            34        264.0
36            98        266.0
37           237        269.0
38           571        274.0
39            72        274.0
40           719        278.0
41           722        281.0
42           162        287.0
43           449        288.0
44           371        305.0
45           361        310.0
46           467        318.0
47           104        321.0
48           450        330.0
49           235        343.0
50           324        359.0
51           279        367.0
52            20        367.0
53           481        368.0
54           521        370.0
55           564        377.0
56           787        381.0
57           354        384.0
58           400        386.0
59            71        386.0
60           495        400.0
61            99        415.0
62           705        418.0
63           785        427.0
64           701        432.0
65           750        439.0
66           437        449.0
67           443        454.0
68           269        462.0
69           395        471.0
70           174        475.0
71           501        476.0
72           700        478.0
73            37        496.0
74           637        528.0
75           387        529.0
76           123        538.0
77           163        551.0
78           128        565.0
79           565        571.0
80           109        583.0
81           221        585.0
82            16        586.0
83           488        594.0
84            65        600.0
85            96        605.0
86           620        615.0
87            64        629.0
88           502        640.0
89           131        641.0
90           477        644.0
91           399        644.0
92            56        649.0
93           118        658.0
94            44        658.0
95            84        659.0
96            22        662.0
97           754        676.0
98           262        684.0
99           606        689.0
100          403        696.0
101          362        710.0
102          585        730.0
103          603        730.0
104          331        738.0
105           39        738.0
106          636        740.0
107          586        741.0
108          535        742.0
109          767        742.0
110          338        744.0
111           66        744.0
112          239        756.0
113          471        757.0
114          716        759.0
115          670        764.0
116          551        774.0
117          525        777.0
118          322        785.0
119           85        791.0
120          508        795.0
121          209        798.0
122          105        809.0
123           24        813.0
124          745        816.0
125          265        827.0
126          756        834.0
127           42        835.0
128          144        844.0
129          784        846.0
130          779        847.0
131          531        855.0
132          406        858.0
133           59        862.0
134          379        864.0
135          376        865.0
136          629        878.0
137          319        884.0
138          665        884.0
139          141        885.0
140          663        886.0
141          329        887.0
142            1        887.0
143          394        901.0
144          704        902.0
145          135        906.0
146          426        909.0
147           17        914.0
148          499        922.0
149          278        925.0
150           28        926.0
151          263        934.0
152          510        936.0
153          261        944.0
154          655        947.0
155          120        950.0
156          617        955.0
157          352        955.0
158          393        959.0
159          724        966.0
160          654        968.0
161           10        969.0
162          661        971.0
163          755        974.0
164           70        983.0
165          439        984.0
166          780        994.0
167          116       1006.0
168          482       1007.0
169          621       1008.0
170          479       1009.0
171          689       1019.0
172          748       1024.0
173          543       1031.0
174          742       1038.0
175          272       1041.0
176          244       1042.0
177          726       1044.0
178          199       1051.0
179           25       1056.0
180           23       1056.0
181          358       1057.0
182          786       1057.0
183          612       1057.0
184          210       1059.0
185          599       1062.0
186          165       1076.0
187          212       1079.0
188          223       1081.0
189          365       1082.0
190          682       1085.0
191          369       1092.0
192          764       1095.0
193           11       1114.0
194          202       1122.0
195          378       1130.0
196          653       1137.0
197          126       1138.0
198          444       1145.0
199          167       1148.0
200          243       1156.0
201          377       1157.0
202           29       1172.0
203          218       1175.0
204           82       1181.0
205          277       1187.0
206          523       1203.0
207          238       1205.0
208          151       1206.0
209          341       1215.0
210          266       1220.0
211          588       1220.0
212          578       1229.0
213          524       1241.0
214          763       1245.0
215          256       1245.0
216          396       1245.0
217          507       1253.0
218          711       1255.0
219          299       1255.0
220          533       1257.0
221          474       1259.0
222          125       1262.0
223          242       1267.0
224          720       1271.0
225          597       1278.0
226          122       1279.0
227          303       1285.0
228          228       1298.0
229          317       1299.0
230          175       1300.0
231          252       1302.0
232          504       1304.0
233          702       1306.0
234          483       1315.0
235          699       1319.0
236          196       1321.0
237          537       1321.0
238          675       1324.0
239           67       1336.0
240          119       1338.0
241          680       1341.0
242          512       1342.0
243          470       1347.0
244          677       1348.0
245          298       1362.0
246          234       1378.0
247          283       1383.0
248          771       1387.0
249          364       1388.0
250          561       1397.0
251          187       1397.0
252          314       1400.0
253          595       1405.0
254          372       1418.0
255          553       1420.0
256          647       1420.0
257          153       1423.0
258          404       1428.0
259          538       1429.0
260          747       1429.0
261          732       1435.0
262          593       1441.0
263          624       1453.0
264           35       1455.0
265          609       1457.0
266          220       1458.0
267          619       1460.0
268          101       1460.0
269          584       1467.0
270          453       1469.0
271          736       1470.0
272          145       1475.0
273          793       1494.0
274          190       1504.0
275          386       1507.0
276           40       1515.0
277          434       1520.0
278           83       1522.0
279          115       1527.0
280          137       1537.0
281          108       1539.0
282          486       1547.0
283          498       1561.0
284          580       1567.0
285          420       1568.0
286          301       1569.0
287          344       1571.0
288          541       1582.0
289          183       1583.0
290           81       1586.0
291           13       1588.0
292          181       1600.0
293          749       1603.0
294          513       1611.0
295           50       1624.0
296           48       1639.0
297          264       1644.0
298          164       1659.0
299          140       1662.0
300          363       1669.0
301          121       1676.0
302          136       1679.0
303          519       1686.0
304          427       1686.0
305          662       1686.0
306          198       1687.0
307           77       1698.0
308          408       1706.0
309          770       1707.0
310          226       1712.0
311           97       1728.0
312          368       1733.0
313          545       1736.0
314          778       1736.0
315            8       1736.0
316           80       1738.0
317          476       1740.0
318            2       1744.0
319          549       1759.0
320          201       1762.0
321          139       1771.0
322          359       1791.0
323           32       1792.0
324          350       1804.0
325          574       1822.0
326          600       1823.0
327          582       1832.0
328          259       1833.0
329           63       1839.0
330          591       1841.0
331          703       1861.0
332          185       1861.0
333          556       1871.0
334          113       1873.0
335          709       1873.0
336          695       1875.0
337          468       1880.0
338          697       1885.0
339          305       1888.0
340          422       1889.0
341          728       1903.0
342          514       1908.0
343          356       1912.0
344          351       1934.0
345          769       1937.0
346          160       1949.0
347          466       1963.0
348          684       1966.0
349          576       1974.0
350          592       1988.0
351          240       1989.0
352          320       1991.0
353          781       2006.0
354          227       2012.0
355          572       2031.0
356          127       2035.0
357           58       2052.0
358          761       2054.0
359          475       2060.0
360          646       2068.0
361          516       2071.0
362          774       2074.0
363          639       2086.0
364          708       2096.0
365          469       2096.0
366          416       2122.0
367          245       2139.0
368          171       2149.0
369          385       2153.0
370          247       2161.0
371          743       2162.0
372          567       2163.0
373          326       2163.0
374          656       2169.0
375          429       2171.0
376          193       2172.0
377          692       2180.0
378          583       2182.0
379           93       2188.0
380          306       2190.0
381          751       2198.0
382          251       2200.0
383          413       2202.0
384          518       2203.0
385          348       2204.0
386          614       2207.0
387          206       2215.0
388          560       2219.0
389          539       2220.0
390          309       2222.0
391           27       2235.0
392          454       2239.0
393          353       2241.0
394          765       2243.0
395          440       2245.0
396          491       2255.0
397          411       2257.0
398          506       2258.0
399          414       2261.0
400           94       2262.0
401          177       2271.0
402          289       2273.0
403          345       2280.0
404          446       2280.0
405          459       2298.0
406          526       2302.0
407          148       2306.0
408          213       2333.0
409          254       2340.0
410          648       2342.0
411          511       2351.0
412          179       2354.0
413           33       2356.0
414          340       2358.0
415          569       2368.0
416          360       2371.0
417          172       2372.0
418          186       2372.0
419          789       2375.0
420          208       2391.0
421          485       2393.0
422          739       2423.0
423          505       2427.0
424           73       2442.0
425          532       2453.0
426          777       2454.0
427          302       2454.0
428          106       2455.0
429          496       2456.0
430          280       2456.0
431          555       2461.0
432           86       2472.0
433          142       2473.0
434          457       2477.0
435          528       2477.0
436          570       2487.0
437          590       2494.0
438           31       2495.0
439          233       2502.0
440          402       2518.0
441          401       2519.0
442          291       2523.0
443          143       2533.0
444          332       2534.0
445           41       2538.0
446          173       2541.0
447          216       2551.0
448          117       2564.0
449          500       2565.0
450          253       2567.0
451           87       2568.0
452          566       2576.0
453          712       2578.0
454           18       2584.0
455          327       2586.0
456          710       2596.0
457          688       2603.0
458          425       2618.0
459          618       2619.0
460          150       2649.0
461          205       2652.0
462          276       2657.0
463          628       2663.0
464          573       2673.0
465          286       2681.0
466           90       2682.0
467          102       2684.0
468          410       2698.0
469          357       2710.0
470          492       2723.0
471          389       2726.0
472          484       2727.0
473          455       2740.0
474          438       2745.0
475          536       2752.0
476          149       2757.0
477          257       2768.0
478          610       2770.0
479          384       2773.0
480          643       2787.0
481          773       2798.0
482           69       2799.0
483          293       2819.0
484          772       2820.0
485          152       2832.0
486          412       2834.0
487          197       2840.0
488          462       2845.0
489          268       2846.0
490          178       2854.0
491          161       2869.0
492          336       2872.0
493          598       2875.0
494          211       2882.0
495           68       2889.0
496          520       2890.0
497          563       2894.0
498          182       2900.0
499          638       2913.0
500          493       2922.0
501          696       2922.0
502          407       2933.0
503           75       2934.0
504          473       2935.0
505          740       2942.0
506          154       2946.0
507          733       2955.0
508          575       2966.0
509          207       2974.0
510          281       2984.0
511          534       2986.0
512          464       2989.0
513          129       3038.0
514          184       3040.0
515            3       3051.0
516          676       3053.0
517          693       3056.0
518          430       3058.0
519          753       3059.0
520          542       3062.0
521          273       3073.0
522          296       3078.0
523          274       3084.0
524          587       3088.0
525          423       3102.0
526          706       3126.0
527          713       3128.0
528          735       3129.0
529          659       3134.0
530          517       3146.0
531          415       3152.0
532          146       3154.0
533          349       3158.0
534          366       3175.0
535          219       3195.0
536          112       3197.0
537          156       3201.0
538          497       3207.0
539           19       3215.0
540          627       3221.0
541          465       3232.0
542          694       3234.0
543          249       3236.0
544          132       3241.0
545          463       3247.0
546          330       3250.0
547            5       3251.0
548            6       3255.0
549          188       3256.0
550          342       3257.0
551          194       3274.0
552          641       3280.0
553          111       3288.0
554          107       3288.0
555          634       3301.0
556          622       3310.0
557          421       3313.0
558          224       3318.0
559           61       3324.0
560          189       3336.0
561          730       3338.0
562          230       3343.0
563          241       3357.0
564          782       3361.0
565          667       3364.0
566          775       3368.0
567          671       3406.0
568          664       3408.0
569          282       3419.0
570          679       3424.0
571          601       3454.0
572          258       3487.0
573           45       3489.0
574          645       3495.0
575          267       3511.0
576          232       3540.0
577          295       3583.0
578          744       3589.0
579          632       3622.0
580          668       3628.0
581          674       3630.0
582          367       3638.0
583          246       3643.0
584          159       3651.0
585          472       3654.0
586           79       3676.0
587          334       3690.0
588          683       3732.0
589          285       3737.0
590          405       3748.0
591          374       3762.0
592          489       3766.0
593          509       3785.0
594          130       3789.0
595          527       3793.0
596          522       3805.0
597          651       3816.0
598          581       3819.0
599           49       3831.0
600          658       3832.0
601          391       3868.0
602           92       3888.0
603          288       3890.0
604          435       3908.0
605          577       3909.0
606          236       3909.0
607          147       3914.0
608          441       3920.0
609          615       3922.0
610          300       3922.0
611          478       3931.0
612          686       3980.0
613          530       3984.0
614          180       3985.0
615          727       3990.0
616          287       4047.0
617          311       4073.0
618          222       4074.0
619          718       4106.0
620          608       4115.0
621          552       4151.0
622          650       4160.0
623          294       4172.0
624          370       4198.0
625           89       4205.0
626          768       4234.0
627          168       4247.0
628          284       4257.0
629           15       4262.0
630          752       4266.0
631          631       4272.0
632          192       4283.0
633          723       4283.0
634          503       4300.0
635          557       4329.0
636          715       4345.0
637          297       4355.0
638          255       4358.0
639          681       4374.0
640           57       4376.0
641          100       4410.0
642          428       4418.0
643          346       4427.0
644          494       4433.0
645          741       4456.0
646          461       4492.0
647          717       4494.0
648           53       4501.0
649           60       4511.0
650           55       4523.0
651          203       4532.0
652          275       4589.0
653          669       4626.0
654          431       4642.0
655          217       4655.0
656          271       4657.0
657          452       4705.0
658          630       4714.0
659          304       4717.0
660          766       4737.0
661           74       4752.0
662          375       4762.0
663          721       4767.0
664          660       4794.0

In [ ]:
# 6. What is the most profitable city in the State of Tennessee?
query = """
SELECT o.shipping_city, SUM(od.order_profits)
FROM order_details od
JOIN orders o
USING (order_id)
WHERE o.shipping_state = 'Tennessee'
GROUP BY o.shipping_city
ORDER BY SUM(od.order_profits) DESC
LIMIT 1;
"""

display(pd.read_sql(sa.text(query),connection))

  shipping_city   sum
0       Lebanon  83.0

In [ ]:
# 7. What’s the average annual profit for that city across all years?
query = """
SELECT AVG(od.order_profits) AS avg_annual_profit
FROM order_details od
JOIN orders o
USING (order_id)
WHERE o.shipping_city = 'Lebanon';
"""

display(pd.read_sql(sa.text(query),connection))

   avg_annual_profit
0          27.666667

In [ ]:
# 8. What is the distribution of customer types in the data?
query = """
SELECT customer_segment, COUNT(customer_id) AS num_customers
FROM customers
GROUP BY customer_segment;
"""

display(pd.read_sql(sa.text(query),connection))

  customer_segment  num_customers
0         Consumer            410
1        Corporate            237
2      Home Office            148

In [ ]:
# 9. What’s the most profitable product category on average in Iowa across all years?
query = """
SELECT p.product_category, AVG(od.order_profits) AS average_profit
FROM orders o
JOIN order_details od
ON o.order_id = od.order_id
JOIN product p
ON od.product_id = p.product_id
WHERE o.shipping_state = 'Iowa'
GROUP BY p.product_category
ORDER BY average_profit DESC
LIMIT 1;
"""

display(pd.read_sql(sa.text(query),connection))

  product_category  average_profit
0        Furniture          130.25

In [ ]:
# 10. What is the most popular product in that category across all states in 2016?
query = """
SELECT p.product_name, SUM(od.quantity) AS total_quantity
FROM orders o
JOIN order_details od
ON o.order_id = od.order_id
JOIN product p
ON od.product_id = p.product_id
WHERE p.product_category = 'Furniture'
			AND EXTRACT(YEAR FROM o.order_date) = 2016
GROUP BY p.product_name
ORDER BY SUM(od.quantity) DESC
LIMIT 1;
"""

display(pd.read_sql(sa.text(query),connection))

                                 product_name  total_quantity
0  Global Push Button Manager's Chair, Indigo            22.0

In [ ]:
# 11. Which customer got the most discount in the data? (in total amount)
query = """
SELECT
   o.customer_id,
   SUM( (order_sales / (1 - order_discount)) - order_sales ) AS total_of_discount
FROM order_details od
JOIN orders o ON o.order_id = od.order_id
JOIN customers c ON o.customer_id= c.customer_id
GROUP BY o.customer_id
ORDER BY total_of_discount DESC
LIMIT 1;
"""

display(pd.read_sql(sa.text(query),connection))

   customer_id  total_of_discount
0          687       23929.083333

In [ ]:
# 12. How widely did monthly profits vary in 2018?
query = """
SELECT *,
    (month_total- LAG(month_total, 1, 0) OVER() ) AS month_diff
FROM
(
     SELECT to_char(order_date, 'MM-YYYY') AS month,
            SUM(order_profits) AS month_total
     FROM orders
     JOIN order_details USING(order_id)
     WHERE EXTRACT(YEAR FROM order_date) = 2018
     GROUP BY month
) as a
ORDER BY month;
"""

display(pd.read_sql(sa.text(query),connection))

      month  month_total  month_diff
0   01-2018       7137.0      7137.0
1   02-2018       1612.0     -5525.0
2   03-2018      14758.0     13146.0
3   04-2018        934.0    -13824.0
4   05-2018       6342.0      5408.0
5   06-2018       8226.0      1884.0
6   07-2018       6951.0     -1275.0
7   08-2018       9034.0      2083.0
8   09-2018      10987.0      1953.0
9   10-2018       9272.0     -1715.0
10  11-2018       9217.0       -55.0
11  12-2018       8473.0      -744.0

In [ ]:
# 13. Which was the biggest order regarding sales in 2015?
query = """
SELECT
		od.order_id,
    SUM(od.order_sales) AS total_sales

FROM order_details od

JOIN orders o ON od.order_id = o.order_id

WHERE EXTRACT(YEAR FROM o.order_date) = 2015

GROUP BY od.order_id
ORDER BY total_sales DESC
LIMIT 1;
"""

display(pd.read_sql(sa.text(query),connection))

         order_id  total_sales
0  CA-2015-145317      23660.0

In [ ]:
# 14. What was the rank of each city in the East region in 2015 in quantity?
query = """
SELECT
		o.shipping_city,
    SUM(od.quantity) AS total_quantity,
    RANK() OVER (ORDER BY SUM(od.quantity) DESC) AS rank

FROM order_details od

JOIN orders o ON od.order_id = o.order_id

WHERE EXTRACT(YEAR FROM o.order_date) = 2015
AND o.shipping_region = 'East'

GROUP BY o.shipping_city
ORDER BY rank;
"""

display(pd.read_sql(sa.text(query),connection))

    shipping_city  total_quantity  rank
0   New York City          1708.0     1
1    Philadelphia           403.0     2
2        Columbus           167.0     3
3          Newark            64.0     4
4       Fairfield            53.0     5
5      Long Beach            44.0     6
6        Lakewood            38.0     7
7       Lancaster            36.0     8
8        Lawrence            31.0     9
9           Dover            30.0    10
10     Hackensack            28.0    11
11         Bangor            24.0    12
12          Utica            24.0    12
13         Lowell            23.0    14
14        Yonkers            22.0    15
15     Wilmington            21.0    16
16        Clinton            20.0    17
17      Baltimore            20.0    17
18       Cranston            20.0    17
19        Everett            19.0    20
20     Providence            19.0    20
21        Buffalo            19.0    20
22         Medina            16.0    23
23        Meriden            15.0    24
24        Beverly            15.0    24
25   New Rochelle            14.0    26
26        Bristol            14.0    26
27      Hempstead            12.0    28
28      Cleveland            12.0    28
29      Rochester            12.0    28
30         Toledo            12.0    28
31      Watertown            12.0    28
32        Chester            11.0    33
33           Troy            11.0    33
34       Franklin            11.0    33
35          Akron            10.0    36
36        Clifton             9.0    37
37      Jamestown             9.0    37
38        Concord             9.0    37
39       Columbia             8.0    40
40         Lorain             8.0    40
41       Hamilton             8.0    40
42     Cincinnati             8.0    40
43          Mason             7.0    44
44   Mount Vernon             7.0    44
45         Linden             7.0    44
46        Reading             6.0    47
47         Revere             6.0    47
48           Kent             5.0    49
49      Oceanside             5.0    49
50    Springfield             5.0    49
51         Orange             4.0    52
52          Parma             4.0    52
53  Niagara Falls             3.0    54
54     Plainfield             3.0    54
55         Marion             3.0    54
56  Bowling Green             2.0    57
57       Freeport             2.0    57
58     Middletown             2.0    57
59     Woonsocket             2.0    57

In [ ]:
# 15. Display customer names for customers who are in the segment ‘Consumer’ or ‘Corporate.’ How many customers are there in total?
query = """
SELECT
    customer_segment, customer_name,
    COUNT(*) OVER (PARTITION BY customer_segment) AS segment_count,
    COUNT(*) OVER () AS total_customers

FROM customers

WHERE customer_segment IN ('Consumer', 'Corporate')

ORDER BY customer_segment, customer_name;
"""

display(pd.read_sql(sa.text(query),connection))

    customer_segment           customer_name  segment_count  total_customers
0           Consumer           Aaron Bergman            410              647
1           Consumer      Adam Shillingsburg            410              647
2           Consumer           Adrian Barton            410              647
3           Consumer             Aimee Bixby            410              647
4           Consumer             Alan Barnes            410              647
5           Consumer              Alan Hwang            410              647
6           Consumer            Alan Shonely            410              647
7           Consumer         Alejandro Grove            410              647
8           Consumer              Alex Avila            410              647
9           Consumer            Alex Grayson            410              647
10          Consumer            Allen Armold            410              647
11          Consumer          Allen Goldenen            410              647
12          Consumer                 Amy Cox            410              647
13          Consumer                Amy Hunt            410              647
14          Consumer            Andrew Allen            410              647
15          Consumer          Andrew Roberts            410              647
16          Consumer             Andy Reiter            410              647
17          Consumer          Anemone Ratner            410              647
18          Consumer             Angele Hood            410              647
19          Consumer           Anna Andreadi            410              647
20          Consumer              Anna Chung            410              647
21          Consumer             Anna Gayman            410              647
22          Consumer          Anne McFarland            410              647
23          Consumer           Annie Thurman            410              647
24          Consumer            Annie Zypern            410              647
25          Consumer            Anthony Witt            410              647
26          Consumer          Arianne Irving            410              647
27          Consumer            Art Ferguson            410              647
28          Consumer              Art Foster            410              647
29          Consumer           Arthur Gainer            410              647
30          Consumer          Arthur Prichep            410              647
31          Consumer           Ashley Jarboe            410              647
32          Consumer            Astrea Jones            410              647
33          Consumer          Barry Gonzalez            410              647
34          Consumer           Barry Weirich            410              647
35          Consumer               Bart Folk            410              647
36          Consumer            Becky Martin            410              647
37          Consumer               Becky Pak            410              647
38          Consumer             Ben Wallace            410              647
39          Consumer      Benjamin Patterson            410              647
40          Consumer          Berenike Kampe            410              647
41          Consumer              Beth Paige            410              647
42          Consumer          Bill Donatelli            410              647
43          Consumer             Bobby Elias            410              647
44          Consumer           Bobby Odegard            410              647
45          Consumer           Bobby Trafton            410              647
46          Consumer         Bradley Drucker            410              647
47          Consumer          Bradley Nguyen            410              647
48          Consumer            Brian Dahlen            410              647
49          Consumer         Brian DeCherney            410              647
50          Consumer              Brian Derr            410              647
51          Consumer           Brian Stugart            410              647
52          Consumer          Brian Thompson            410              647
53          Consumer         Brosina Hoffman            410              647
54          Consumer        Bruce Degenhardt            410              647
55          Consumer              Bruce Geld            410              647
56          Consumer           Bruce Stewart            410              647
57          Consumer             Bryan Davis            410              647
58          Consumer             Bryan Mills            410              647
59          Consumer         Cari Schnelling            410              647
60          Consumer             Carl Ludwig            410              647
61          Consumer             Carlos Daly            410              647
62          Consumer           Carlos Meador            410              647
63          Consumer          Carlos Soltero            410              647
64          Consumer            Carol Darley            410              647
65          Consumer            Carol Triggs            410              647
66          Consumer         Caroline Jumper            410              647
67          Consumer       Cassandra Brandow            410              647
68          Consumer            Chad McGuire            410              647
69          Consumer            Chad Sievert            410              647
70          Consumer        Charles Crestani            410              647
71          Consumer       Charles McCrossin            410              647
72          Consumer        Charlotte Melton            410              647
73          Consumer     Chloris Kastensmidt            410              647
74          Consumer            Chris Cortes            410              647
75          Consumer            Chris McAfee            410              647
76          Consumer      Christina Anderson            410              647
77          Consumer        Christina DeMoss            410              647
78          Consumer  Christina VanderZanden            410              647
79          Consumer    Christine Sundaresam            410              647
80          Consumer      Christopher Conant            410              647
81          Consumer    Christopher Martinez            410              647
82          Consumer        Christy Brittain            410              647
83          Consumer             Chuck Magee            410              647
84          Consumer             Chuck Sachs            410              647
85          Consumer           Cindy Chapman            410              647
86          Consumer           Cindy Stewart            410              647
87          Consumer             Claire Gute            410              647
88          Consumer           Clay Cheatham            410              647
89          Consumer             Clay Ludtke            410              647
90          Consumer            Clytie Kelty            410              647
91          Consumer              Corey-Lock            410              647
92          Consumer          Craig Carreira            410              647
93          Consumer           Craig Carroll            410              647
94          Consumer            Craig Reiter            410              647
95          Consumer         Cynthia Arntzen            410              647
96          Consumer            Dan Campbell            410              647
97          Consumer              Dan Lawera            410              647
98          Consumer             Dana Kaydos            410              647
99          Consumer             Daniel Lacy            410              647
100         Consumer          Darren Koutras            410              647
101         Consumer           Darren Powers            410              647
102         Consumer           Darrin Martin            410              647
103         Consumer             Dave Brooks            410              647
104         Consumer               Dave Kipp            410              647
105         Consumer          David Flashing            410              647
106         Consumer          David Philippe            410              647
107         Consumer             Dean Braden            410              647
108         Consumer            Debra Catini            410              647
109         Consumer       Delfina Latchford            410              647
110         Consumer       Denise Leinenbach            410              647
111         Consumer             Dennis Kane            410              647
112         Consumer           Denny Blanton            410              647
113         Consumer            Denny Ordway            410              647
114         Consumer        Dianna Vittorini            410              647
115         Consumer               Don Weiss            410              647
116         Consumer       Dorothy Dickinson            410              647
117         Consumer           Doug Bickford            410              647
118         Consumer             Doug Jacobs            410              647
119         Consumer          Doug O'Connell            410              647
120         Consumer            Duane Benoit            410              647
121         Consumer            Duane Noonan            410              647
122         Consumer               Ed Jacobs            410              647
123         Consumer           Edward Nazzal            410              647
124         Consumer             Emily Burns            410              647
125         Consumer             Emily Grady            410              647
126         Consumer              Emily Phan            410              647
127         Consumer            Eric Barreto            410              647
128         Consumer           Eric Hoffmann            410              647
129         Consumer            Eric Murdock            410              647
130         Consumer           Erica Hackney            410              647
131         Consumer             Erica Smith            410              647
132         Consumer          Erin Creighton            410              647
133         Consumer               Erin Mull            410              647
134         Consumer          Eugene Barchas            410              647
135         Consumer              Eva Jacobs            410              647
136         Consumer           Evan Bailliet            410              647
137         Consumer              Evan Henry            410              647
138         Consumer             Frank Olsen            410              647
139         Consumer             Frank Preis            410              647
140         Consumer             Fred Harton            410              647
141         Consumer             Fred McMath            410              647
142         Consumer              Gary Hwang            410              647
143         Consumer             Gary McGarr            410              647
144         Consumer           Gary Zandusky            410              647
145         Consumer            Gene McClure            410              647
146         Consumer         George Ashbrook            410              647
147         Consumer       Giulietta Baptist            410              647
148         Consumer        Giulietta Weimer            410              647
149         Consumer             Greg Hansen            410              647
150         Consumer           Greg Matthias            410              647
151         Consumer               Greg Tran            410              647
152         Consumer           Guy Armstrong            410              647
153         Consumer            Guy Thornton            410              647
154         Consumer            Harry Greene            410              647
155         Consumer           Helen Abelman            410              647
156         Consumer          Helen Andreada            410              647
157         Consumer             Henia Zydlo            410              647
158         Consumer       Henry MacAllister            410              647
159         Consumer         Herbert Flentye            410              647
160         Consumer           Hunter Glantz            410              647
161         Consumer            Hunter Lopez            410              647
162         Consumer           Ionia McGrath            410              647
163         Consumer            Irene Maddox            410              647
164         Consumer             Ivan Gibson            410              647
165         Consumer             Ivan Liston            410              647
166         Consumer              Jack Garza            410              647
167         Consumer             Jack Lebron            410              647
168         Consumer            James Galang            410              647
169         Consumer            Jamie Frazer            410              647
170         Consumer            Jamie Kunitz            410              647
171         Consumer               Janet Lee            410              647
172         Consumer            Janet Martin            410              647
173         Consumer           Jas O'Carroll            410              647
174         Consumer          Jason Fortune-            410              647
175         Consumer         Jasper Cacioppo            410              647
176         Consumer                Jay Fein            410              647
177         Consumer              Jay Kimmel            410              647
178         Consumer            Jenna Caffey            410              647
179         Consumer       Jennifer Ferguson            410              647
180         Consumer       Jennifer Halladay            410              647
181         Consumer        Jennifer Jackson            410              647
182         Consumer          Jeremy Ellison            410              647
183         Consumer            Jeremy Farry            410              647
184         Consumer         Jeremy Lonsdale            410              647
185         Consumer           Jeremy Pistek            410              647
186         Consumer          Jessica Myrick            410              647
187         Consumer              Jill Fjeld            410              647
188         Consumer           Jill Matthias            410              647
189         Consumer            Jim Karlsson            410              647
190         Consumer             Jim Radford            410              647
191         Consumer          Jocasta Rupert            410              647
192         Consumer              Joe Elijah            410              647
193         Consumer           Joe Kamberova            410              647
194         Consumer              Joel Eaton            410              647
195         Consumer            John Castell            410              647
196         Consumer              John Dryer            410              647
197         Consumer             John Huston            410              647
198         Consumer                John Lee            410              647
199         Consumer              John Lucas            410              647
200         Consumer             John Murray            410              647
201         Consumer          John Stevenson            410              647
202         Consumer         Jonathan Howell            410              647
203         Consumer          Joni Blumstein            410              647
204         Consumer          Joni Wasserman            410              647
205         Consumer            Joseph Airdo            410              647
206         Consumer             Joseph Holt            410              647
207         Consumer               Joy Bell-            410              647
208         Consumer             Joy Daniels            410              647
209         Consumer               Joy Smith            410              647
210         Consumer            Julia Dunbar            410              647
211         Consumer              Julia West            410              647
212         Consumer           Juliana Krohn            410              647
213         Consumer            Justin Hirsh            410              647
214         Consumer      Justin MacKendrick            410              647
215         Consumer           Karen Daniels            410              647
216         Consumer              Karl Braun            410              647
217         Consumer        Katherine Ducich            410              647
218         Consumer        Katherine Hughes            410              647
219         Consumer         Katrina Willman            410              647
220         Consumer           Kean Takahito            410              647
221         Consumer           Kean Thornton            410              647
222         Consumer           Keith Herrera            410              647
223         Consumer          Kelly Andreada            410              647
224         Consumer         Kelly Collister            410              647
225         Consumer          Kelly Williams            410              647
226         Consumer            Ken Lonsdale            410              647
227         Consumer            Khloe Miller            410              647
228         Consumer            Kunst Miller            410              647
229         Consumer            Larry Blacks            410              647
230         Consumer            Larry Hughes            410              647
231         Consumer              Larry Tron            410              647
232         Consumer         Laurel Elliston            410              647
233         Consumer      Lauren Leatherbury            410              647
234         Consumer           Lena Cacioppo            410              647
235         Consumer          Lena Creighton            410              647
236         Consumer          Lena Hernandez            410              647
237         Consumer            Lena Radford            410              647
238         Consumer          Lisa DeCherney            410              647
239         Consumer             Lisa Hazard            410              647
240         Consumer            Liz Carlisle            410              647
241         Consumer         Liz MacKendrick            410              647
242         Consumer           Liz Pelletier            410              647
243         Consumer               Liz Preis            410              647
244         Consumer            Liz Thompson            410              647
245         Consumer          Liz Willingham            410              647
246         Consumer            Logan Currie            410              647
247         Consumer        Logan Haushalter            410              647
248         Consumer             Luke Foster            410              647
249         Consumer              Luke Weiss            410              647
250         Consumer        Lycoris Saunders            410              647
251         Consumer              Lynn Smith            410              647
252         Consumer         Magdelene Morse            410              647
253         Consumer              Marc Crier            410              647
254         Consumer         Maria Bertelson            410              647
255         Consumer           Maribeth Dona            410              647
256         Consumer     Maribeth Schnelling            410              647
257         Consumer            Maris LaWare            410              647

In [ ]:
# 16. Calculate the difference between the largest and smallest order quantities for product id ‘100.’
query = """
SELECT MAX(od.quantity) - MIN(od.quantity) AS dif
FROM order_details od
WHERE od.product_id = 100
GROUP BY od.product_id
"""

display(pd.read_sql(sa.text(query),connection))

   dif
0    4

In [ ]:
# 17. Calculate the percent of products that are within the category ‘Furniture.’
query = """
SELECT CAST(COUNT(product_id) AS decimal)/(SELECT COUNT(product_id) FROM product) * 100 AS pct_furniture
FROM product p
WHERE p.product_category = 'Furniture'
"""

display(pd.read_sql(sa.text(query),connection))

   pct_furniture
0      20.540541

In [ ]:
# 18. Display the number of product manufacturers with more than 1 product in the product table.
query = """
SELECT COUNT(*) FROM
(SELECT DISTINCT p.product_manufacturer
FROM product p
GROUP BY p.product_manufacturer
HAVING COUNT(p.product_id) > 1) AS nr_of_mans
"""

display(pd.read_sql(sa.text(query),connection))

   count
0    169

In [ ]:
# 19.Show the product_subcategory and the total number of products in the subcategory. Show the order for the most to least number of products.
query = """
SELECT p.product_subcategory, COUNT(p.product_id)
FROM product p
GROUP BY p.product_subcategory
ORDER BY 2 DESC
"""

display(pd.read_sql(sa.text(query),connection))

   product_subcategory  count
0                Paper    277
1              Binders    211
2               Phones    189
3          Furnishings    186
4                  Art    157
5          Accessories    147
6              Storage    132
7           Appliances     97
8               Chairs     88
9               Labels     70
10            Machines     63
11              Tables     56
12           Bookcases     50
13           Envelopes     44
14            Supplies     36
15           Fasteners     34
16             Copiers     13

In [ ]:
# 20. Show the product_id(s), the sum of quantities, where for each sale of product quantities is greater than or equal to 100.
query = """
SELECT od.product_id, od.quantity
FROM order_details od
WHERE od.quantity >= 100
ORDER BY od.product_id
"""

display(pd.read_sql(sa.text(query),connection))

   product_id  quantity
0         122       143
1         920       130
2        1507       324
3        1600       216